#!/bin/sh
./rays.debug -i dat/tables.bin -o tables.bmp -D demd.bmp -S sign.bmp -p part.bmp -P fatal.bmp -r 32 -R sign_ab.bmp -b 64 -x 1024 -y 768 -s 1 -n 1.3 -N -m .2 -a .3 -q 95 -B -A -K -2 -J -g -N -R sign_ab.bmp
# -t 3000 -G
