#!/bin/sh
gcc -O4 --save-temps -Wall -ansi -pedantic -pthread -DDEBUG -fprofile-arcs -ftest-coverage -I/usr/local/include -I/usr/X11R6/include -L/usr/local/lib -L/usr/X11R6/lib -o rays.gcov rays.c -lc -lm -lglut -ljpeg

